name: GitHubCI
on:
   push:
     branches: [ "WF-K9" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: nexgang/ubuntu:latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up ccache
        run: |
          echo "CCACHE_DIR=${{ github.workspace }}/.ccache" >> $GITHUB_ENV
          echo "PATH=/usr/lib/ccache/bin:$PATH" >> $GITHUB_ENV
          mkdir -p ${{ github.workspace }}/.ccache
          ccache --max-size=5G

      - name: Restore ccache from cache
        id: cache-ccache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ github.ref_name }}
            ccache-${{ runner.os }}-

      - name: Display initial ccache stats
        run: ccache --show-stats

      - name: Build RDP Kernel
        run: |
          git clone --depth=1 https://ImSpiDy:${{ secrets.GH_TOKEN }}@github.com/ImSpiDy/kernel_xiaomi_lavender-4.19 kernel -b zx
          cd kernel
          bash build.sh --KSU --RDP
          bash build.sh --KSU --ORDP

      - name: Display final ccache stats
        run: |
          echo "======= FINAL CCACHE STATS ======="
          ccache --show-stats

      - name: Save ccache to cache
        uses: actions/cache/save@v4
        if: always()
        with:
          path: ${{ github.workspace }}/.ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
